site_name: passGen documentation
site_url: https://josh-wong.github.io/passGen/
site_description: A lightweight Windows app for creating randomly generated, 14-character passwords.

# Add repo details in the top right-hand corner
repo_name: josh-wong/passGen
repo_url: https://github.com/josh-wong/passGen/
edit_uri: blob/main/docs

plugins:
  - search
  #- techdocs-core
  - git-committers:
      repository: josh-wong/passGen
      branch: main
  - git-revision-date-localized:
      type: date
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "300px"
  - rss:
      abstract_chars_count: 160  # -1 for full content
      categories:
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 20
      pretty_print: false
      match_path: ".*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"

markdown_extensions:
  # Add styles for buttons
  - attr_list
  # Add emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # Add support for Material for MkDocs admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      # Add link next to header that allows the user to get a permalink to the heading (still need to copy the URL in the address bar).
      permalink: true

theme:
  name: material
  # Extend the theme
  custom_dir: overrides
  # Add favicon to browser tab
  favicon: assets/images/favicon.png
  # Add logo to docs pages
  logo: assets/images/mkdocs_passgen_logo.png
  icon:
    # Add icon to show repository information and link
    repo: fontawesome/brands/github
    # Add icons for Material for MkDocs admonitions
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: light blue
      accent: blue
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: light blue
      accent: blue
  features:
    # Mark announcement as read
    - announce.dismiss
    # Add support for improved tooltips
    - content.tooltips
    # Add custom search functions
    - search.highlight
    - search.share
    - search.suggest
    # Add custom navigation functions
    - navigation.expand
    #- navigation.indexes
    - navigation.instant
    #- navigation.sections
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/josh-wong
      name: josh-wong on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wongjoshua
      name: Joshua Wong on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/josh_in_japan
      name: josh_in_japan on Twitter

nav:
  - Overview: 'index.md'
  - Generating a password: 'generating-passwords.md'
  - Updating the app: 'updating-the-app.md'
  - Uninstalling the app: 'uninstalling.md'
  - References: 'references.md'
  - Contributions: 'contributions.md'
  - '': ''
  - 🔶RSS: 'https://josh-wong.github.io/passGen/feed_rss_updated.xml'
  - '': ''
  - '': ''
  - 🏠Home: 'https://josh-wong.github.io'